name = "input-output-hk/contracts-library"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Standardized, reusable smart contracts for Cardano — on-chain validation layer."

[repository]
user = "input-output-hk"
project = "contracts-library"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"

[config]
